### ISSUE TITLE
SQLite em Android

### ISSUE THREAD

**Issue by freitasjca** [antoniojmsjr/MultithreadingFireDAC#2]
Bom dia António, 
Quando se trata de  aplicação a executar no Android , a utilizar código para configurar a connecção  e a utilizar a BD SQLite o código 

      lFDStanConnectionDef.WriteOptions(lFDConnection.FormatOptions,
                                        lFDConnection.UpdateOptions,
                                        lFDConnection.FetchOptions,
                                        lFDConnection.ResourceOptions);

dá erro. "ERROR:External exception B8"
 
Sabe o motivo?

**Comment by freitasjca** [comment]
O mesmo código utilizado em Windows executa sem problema

**Comment by antoniojmsjr** [comment]
> Bom dia António, 
> Quando se trata de  aplicação a executar no Android , a utilizar código para configurar a connecção  e a utilizar a BD SQLite o código 
> 
>       lFDStanConnectionDef.WriteOptions(lFDConnection.FormatOptions,
>                                         lFDConnection.UpdateOptions,
>                                         lFDConnection.FetchOptions,
>                                         lFDConnection.ResourceOptions);
> 
> 
> dá erro. "ERROR:External exception B8"
>  
> Sabe o motivo? 
> 

Boa noite,

Tu já deu uma olhada neste artigo:

https://docwiki.embarcadero.com/RADStudio/Sydney/en/Connect_to_SQLite_database_(FireDAC)

Pode ser que precise fazer deploy de alguns arquivos
